# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1afCwAAF8XFzrxrl8YFqBCZMEZgK5gwvX
"""

#1 addiiton of 2 numbers
#2 check if a given number is odd or even
#3 check if the number is prime or not
#4 largest of 4 numbers
#5 factorial of a number
#6 reversing a number
#7 check string for palindrome
#8 find the sum of digits
#9 create a multiplication table for a given number
#10 make a calculator with 4 operations
#11 Pattern:
# *
# **
# ***
# ****

# 1.
a = int(input("enter first number: "))
b = int(input("enter second number: "))
print(a+b)

# 2.
x = int(input("Enter: "))
if x % 2 == 0:
    print("Even")
else:
    print("Odd")

# 3.
x = int(input("Enter : "))
for i in range(2, x):
    if x % i == 0:
        print("not prime")
        break
else:
    print("prime")

# 4.
a = int(input("enter first number: "))
b = int(input("enter second number: "))
c = int(input("enter third number: "))
d = int(input("enter fourth number: "))
if a > b and a > c and a > d:
    print(a)
elif b > a and b > c and b > d:
    print(b)
elif c > a and c > b and c > d:
    print(c)
else:
    print(d)

# 5.
f = 1
x = int(input("enter a number: "))
for i in range(1, x+1):
    f = f * i
print(f)

#6.
x = int(input("enter a number: "))
reverse = 0
while x > 0:
    reverse = reverse * 10 + x % 10
    x = x // 10
print(reverse)

#7.
x = input("enter a string: ")
if x == x[::-1]:
    print("palindrome")
else:
    print("not palindrome")

#8.
x = int(input("enter a number: "))
sum = 0
while x > 0:
    sum = sum + x % 10
    x = x // 10
print(sum)

#9.
n = float(input("enter number for table: "))
for i in range(1, 11):
  # print(n + "*" + i + "=" + n*i)
  print(n, "x", i, "=", n*i)

#10.
#calculator

print("operations: +, -, *, /")
while True:
  op = input("enter operation: ")
  if op == "+":
    x = int(input("enter number 1: "))
    y = int(input("enter number 2: "))
    print(x + y)

  elif op == "-":
    x = int(input("enter number 1: "))
    y = int(input("enter number 2: "))
    print(x - y)

  elif op == "*":
    x = int(input("enter number 1: "))
    y = int(input("enter number 2: "))
    print(x * y)

  elif op == "/":
    x = int(input("enter number 1: "))
    y = int(input("enter number 2: "))
    print(x / y)

  else:
    break

#11.
x = int(input("enter number of rows: "))
for i in range(1, x+1):
  print("*" * i)