# -*- coding: utf-8 -*-
"""Untitled1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1nmq2kf7iR_TnXFxJmhGxZg4-Dlw5iMhs
"""

import pandas as pd

df = pd.read_csv("/content/FuelConsumption (2).csv")

# print(df.head())

# print(df.tail())

# print(df.columns)

# print(df.shape)

# print(df.columns.tolist())

# print(df.describe())

# print(df.info())

df_ffill = df.copy()
df_ffill['FUELCONSUMPTION_CITY'] = df_ffill['FUELCONSUMPTION_CITY'].fillna(method = 'ffill')
print(df_ffill.isnull().sum)

df_bfill = df.copy()
df_bfill['FUELCONSUMPTION_CITY'] = df_bfill['FUELCONSUMPTION_CITY'].fillna(method = 'bfill')
print(df_bfill.isnull().sum)